"""empty message

Revision ID: 32e271e6c627
Revises: 8900bf98f007
Create Date: 2019-04-24 19:49:11.069364

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32e271e6c627'
down_revision = '8900bf98f007'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('right_part',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event', sa.String(length=64), nullable=True),
    sa.Column('activity', sa.String(length=64), nullable=True),
    sa.Column('interest', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('right_part')
    # ### end Alembic commands ###
