"""empty message

Revision ID: 41ea4fac36d6
Revises: 
Create Date: 2019-05-17 23:03:43.137593

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41ea4fac36d6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('carpool_questions', sa.Column('counter', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('carpool_questions', 'counter')
    # ### end Alembic commands ###
