"""empty message

Revision ID: 5469e23edbb0
Revises: 
Create Date: 2018-12-17 22:04:37.937105

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5469e23edbb0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('s_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=32), nullable=False),
    sa.Column('password', sa.String(length=16), nullable=False),
    sa.Column('power', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('s_id')
    )
    op.create_table('carpool_questions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('s_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=64), nullable=False),
    sa.Column('time', sa.String(length=64), nullable=False),
    sa.Column('destination', sa.String(length=64), nullable=False),
    sa.Column('num', sa.String(length=16), nullable=False),
    sa.Column('contact', sa.String(length=32), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('create_time', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['s_id'], ['users.s_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lost_questions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('s_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=64), nullable=False),
    sa.Column('time', sa.String(length=64), nullable=False),
    sa.Column('location', sa.String(length=64), nullable=False),
    sa.Column('contact', sa.String(length=32), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('picture', sa.String(length=128), nullable=True),
    sa.Column('create_time', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['s_id'], ['users.s_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('play_questions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('s_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=64), nullable=False),
    sa.Column('time', sa.String(length=64), nullable=False),
    sa.Column('location', sa.String(length=64), nullable=False),
    sa.Column('contact', sa.String(length=32), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('create_time', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['s_id'], ['users.s_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('search_questions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('s_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=64), nullable=False),
    sa.Column('time', sa.String(length=64), nullable=False),
    sa.Column('location', sa.String(length=64), nullable=False),
    sa.Column('contact', sa.String(length=32), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('picture', sa.String(length=128), nullable=True),
    sa.Column('create_time', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['s_id'], ['users.s_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('carpool_answers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('s_id', sa.Integer(), nullable=True),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('create_time', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['carpool_questions.id'], ),
    sa.ForeignKeyConstraint(['s_id'], ['users.s_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lost_answers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('s_id', sa.Integer(), nullable=True),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('create_time', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['lost_questions.id'], ),
    sa.ForeignKeyConstraint(['s_id'], ['users.s_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('play_answers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('s_id', sa.Integer(), nullable=True),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('create_time', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['play_questions.id'], ),
    sa.ForeignKeyConstraint(['s_id'], ['users.s_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('search_answers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('s_id', sa.Integer(), nullable=True),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('create_time', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['search_questions.id'], ),
    sa.ForeignKeyConstraint(['s_id'], ['users.s_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('search_answers')
    op.drop_table('play_answers')
    op.drop_table('lost_answers')
    op.drop_table('carpool_answers')
    op.drop_table('search_questions')
    op.drop_table('play_questions')
    op.drop_table('lost_questions')
    op.drop_table('carpool_questions')
    op.drop_table('users')
    # ### end Alembic commands ###
