"""empty message

Revision ID: 85e24a770599
Revises: 41ea4fac36d6
Create Date: 2019-05-17 23:12:02.676369

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85e24a770599'
down_revision = '41ea4fac36d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lost_questions', sa.Column('counter', sa.Integer(), nullable=False))
    op.add_column('play_questions', sa.Column('counter', sa.Integer(), nullable=False))
    op.add_column('search_questions', sa.Column('counter', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('search_questions', 'counter')
    op.drop_column('play_questions', 'counter')
    op.drop_column('lost_questions', 'counter')
    # ### end Alembic commands ###
